[package]
name = "happy-ad-hub"
version = "1.0.0"
description = "Happy Ad Hub - SPA Application"

[[module]]
name = "static-server"
source = "https://registry.wasmer.io/packages/nicovazquez/static-file-server"

[[command]]
name = "serve"
runner = "wasmer.io/runner/wapm/static-web-server"

[fs]
"/public" = "dist"

[[command.annotations.wasi]]
main-args = ["-w", "/public", "--fallback", "/public/index.html", "--port", "80"]
